name: format, lint and test

on:
  - pull_request
jobs:
  all:
    name: format, lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make .venv
      - name: Run formatting checks
        run: |
          .venv/bin/black --check . && .venv/bin/isort --check .
      - name: Run linting
        run: |
          .venv/bin/flake8
      - name: Run tests
        run: |
          make test
